# Copyright (c) The PyAMF Project.
# See LICENSE.txt for details.

"""
Meta data and helper functions for setup
"""

import fnmatch
import os.path
import platform
import shutil

try:
    from Cython.Build import cythonize
    from Cython.Distutils import build_ext

    have_cython = True
except ImportError:
    from setuptools.command.build_ext import build_ext

    have_cython = False


from setuptools.command import sdist
from setuptools import Distribution, Extension


_version = None


class MyDistribution(Distribution):
    """
    This seems to be is the only obvious way to add a global option to
    distutils.

    Provide the ability to disable building the extensions for any called
    command.
    """

    global_options = Distribution.global_options + [
        ('disable-ext', None, 'Disable building extensions.')
    ]

    def finalize_options(self):
        Distribution.finalize_options(self)

        try:
            i = self.script_args.index('--disable-ext')
        except ValueError:
            self.disable_ext = False
        else:
            self.disable_ext = True
            self.script_args.pop(i)


class MyBuildExt(build_ext):
    """
    The companion to L{MyDistribution} that checks to see if building the
    extensions are disabled.
    """

    def run(self, *args, **kwargs):
        if self.distribution.disable_ext:
            return

        build_ext.run(self, *args, **kwargs)


class MySDist(sdist.sdist):
    """
    Generate Cython code for source distributions only when extensions are
    enabled.
    """

    def cythonise(self):
        ext = MyBuildExt(self.distribution)
        ext.initialize_options()
        ext.finalize_options()

        # extend sources with the transpiled C sources
        ext.check_extensions_list(ext.extensions)
        cythonized = cythonize(ext.extensions)
        ext.extensions += cythonized

    def run(self):
        if self.distribution.ext_modules and not have_cython:
            print('ERROR - Cython is required to build source distributions')

            raise SystemExit(1)

        if self.distribution.ext_modules:
            self.cythonise()

        return sdist.sdist.run(self)


def set_version(version):
    global _version

    _version = version


def get_version():
    v = ''
    prev = None

    for x in _version:
        if prev is not None:
            if isinstance(x, int):
                v += '.'

        prev = x
        v += str(x)

    return v.strip('.')


def get_extras_require():
    return {
        'lxml': ['lxml>=6.1.1']
    }


def get_package_data():
    return {
        'cpyamf': ['*.pxd'],
        'pyamf.tests': ['imports/*.py'],
    }


def extra_setup_args():
    """
    Extra kwargs to supply in the call to C{setup}.

    This is used to supply custom commands, not metadata - that should live in
    setup.py itself.
    """
    return {
        'distclass': MyDistribution,
        'cmdclass': {
            'build_ext': MyBuildExt,
            'sdist': MySDist
        },
        'package_data': get_package_data(),
    }


def get_install_requirements():
    """
    Returns a list of dependencies for PyAMF to function correctly on the
    target platform.
    """
    install_requires = ['defusedxml>=0.7.1']

    return install_requires


def write_version_py(filename='pyamf/_version.py'):
    """
    """
    if os.path.exists(filename):
        os.remove(filename)

    content = """\
# THIS FILE IS GENERATED BY PYAMF SETUP.PY
from pyamf.versions import Version

version = Version(*%(version)r)
"""
    a = open(filename, 'wt')

    try:
        a.write(content % {'version': _version})
    finally:
        a.close()


def make_extension(mod_name, **extra_options):
    """
    Tries is best to return an Extension instance based on the mod_name
    """
    base_name = os.path.join(mod_name.replace('.', os.path.sep))

    if have_cython:
        for ext in ['.pyx', '.py']:
            source = base_name + ext

            if os.path.exists(source):
                return Extension(mod_name, [source], **extra_options)

        print('WARNING: Could not find Cython source for %r' % (mod_name,))
    else:
        source = base_name + '.c'

        if os.path.exists(source):
            return Extension(mod_name, [source], **extra_options)

        print('WARNING: Could not build extension for %r, no source found' % (
            mod_name,))


def read(fname):
    with open(os.path.join(os.path.dirname(__file__), fname)) as fp:
        return fp.read()


def get_extensions():
    """
    Return extension modules to build.

    Builds use the pure Python path unless the PEP 517 backend explicitly
    enables the optional Cython extensions.
    """
    if os.environ.get('PY3AMF_BUILD_CYTHON') != '1':
        return []

    if not can_compile_extensions():
        raise RuntimeError(
            'Cython extension build was requested, but CPython, Cython, '
            'and gcc are required')

    extensions = [
        Extension(
            name="cpyamf.amf0",
            sources=["cpyamf/amf0.pyx"]
        ),
        Extension(
            name="cpyamf.amf3",
            sources=["cpyamf/amf3.pyx"]
        ),
        Extension(
            name="cpyamf.codec",
            sources=["cpyamf/codec.pyx"]
        ),
        Extension(
            name="cpyamf.util",
            sources=["cpyamf/util.pyx"]
        ),
    ]

    return extensions


def can_compile_extensions():
    return (
            platform.python_implementation() == "CPython"
            and have_cython
            and shutil.which("gcc") is not None
    )


def get_trove_classifiers():
    """
    Return a list of trove classifiers that are setup dependent.
    """
    classifiers = []

    def dev_status():
        version = get_version()

        if 'dev' in version:
            return 'Development Status :: 2 - Pre-Alpha'
        elif 'alpha' in version:
            return 'Development Status :: 3 - Alpha'
        elif 'beta' in version:
            return 'Development Status :: 4 - Beta'
        else:
            return 'Development Status :: 5 - Production/Stable'

    return classifiers + [dev_status()]


def recursive_glob(path, pattern):
    matches = []

    for root, dirnames, filenames in os.walk(path):
        for filename in fnmatch.filter(filenames, pattern):
            matches.append(os.path.normpath(os.path.join(root, filename)))

    return matches
